version: '3'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  postgres-ssl:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - ./test/certs/server.crt:/var/lib/postgresql/server.crt
      - ./test/certs/server.key:/var/lib/postgresql/server.key
    command: |
      postgres -c 'ssl=on' -c 'ssl_cert_file=/var/lib/postgresql/server.crt' -c 'ssl_key_file=/var/lib/postgresql/server.key'
