version: 2.1

orbs:
  rebar3: tsloughter/rebar3@0.7.0
  codecov: circleci/codecov@0.0.3

executors:
  erlang_postgres:
    docker:
      - image: circleci/erlang:23
        entrypoint: ["/bin/sh"]
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
jobs:

  codecov:
    executor: rebar3/erlang
    steps:
      - attach_workspace:
          at: ~/project/
      - codecov/upload:
          path: _build/test/covertool/pgo.covertool.xml

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - rebar3/compile

      - rebar3/xref:
          requires:
            - rebar3/compile
      - rebar3/dialyzer:
          requires:
            - rebar3/compile
      - rebar3/ct:
          executor: erlang_postgres
          requires:
            - rebar3/compile

      - rebar3/cover:
          requires:
            - rebar3/ct
      - codecov:
          requires:
            - rebar3/cover
